Networks - Examen/API/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from rest_framework import routers
from .viewsets import UsuarioViewSet ,RutinaViewSet,NutricionistaViewSet
app_name = 'API'
router = routers.DefaultRouter()
router.register(u'usuarios',UsuarioViewSet)
router.register(u'nutricionistas',NutricionistaViewSet)
router.register(u'rutinas',RutinaViewSet)
urlpatterns =  [ 

   path('',views.index,name="index"), 
   path('api',include(router.urls)),
   path('delete_mensaje/<int:id>/',views.delete_mensaje,name="delete_mensaje"),
   path('edit_mensaje/<int:id>/',views.edit_mensaje, name="edit_mensaje"),
   
]

Networks - Examen/Networks/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from django.contrib.auth.decorators import login_required
from proyecto.views import Inicio,cerrar_sesion,Rutinas,ListadoUsuariosView
from proyecto.models import Usuario
from API import views


app_name='Networks'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('proyecto/',include(('proyecto.urls_proyecto','proyecto'))),
    path('api/',include(('API.urls'))),
    path('',Inicio.as_view(),name='inicio'),
    path('rutinas/',login_required(Rutinas.as_view()),name='rutinas'),
    path('login/',auth_views.LoginView.as_view(template_name="proyecto/login.html"),name='login'),
    path('logout/',cerrar_sesion,name='logout'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html')),
    path('listar/',ListadoUsuariosView.as_view(template_name='proyecto/listarUsuarios.html'), name='listarUsuario'),
    path('index/',views.index,name='index'),

  

]

Networks - Examen/API/models.py
from django.db import models
from django.utils.deconstruct import deconstructible
import os
from uuid import uuid4

# Create your models here.


@deconstructible
class PathAndRename(object):
    def __init__(self,sub_path):
        self.path =sub_path

    def __call__(self, instance, filename):
         ext = filename.split('.')[-1]
         filename = '{}.{}'.format(uuid4().hex, ext)
         return os.path.join(self.path, filename)   

path_and_rename_imagen = PathAndRename("fotos")


class Mensaje(models.Model):

     usuario =models.CharField(max_length=100)
     rutina =models.CharField(max_length=25)
     mensaje =models.TextField()
     foto =models.ImageField(upload_to=path_and_rename_imagen)



##---------------Rutina ----------------------

#djang agrega id 
class Rutina(models.Model):

    nombreRutina = models.CharField(max_length=50)

def __str__(self):
  return self.nombreRutina

#-------------------USUARIO#---------------------

class Usuario(models.Model):

  username =   models.CharField(max_length=50)
  first_name = models.CharField(max_length=50)
  last_name =  models.CharField(max_length=50)
  email =      models.CharField(max_length=50)
  password = models.CharField(max_length=50)
  rut =    models.CharField(max_length=30, unique=True)

  def __str__(self):
    return self.first_name
# ------------------Nutricionista-------------------#

class Nutricionista(models.Model):

  nombreNutricionista = models.CharField(max_length=50)

Networks - Examen/API/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import Mensaje
# Create your views here.



#--------------------------------------------CREAR  Rutina---------------------------------------------
# crear
def index(request):
    if request.POST:
        print("post")
        usuario =request.POST.get("usuario",False)
        rutina=request.POST.get("rutina",False)
        mensaje = request.POST.get("mensaje",False)
        foto = request.FILES.get("foto",False)
        if foto is False:
            foto = None
        msn = Mensaje(usuario=usuario,rutina=rutina,mensaje=mensaje,foto=foto)
        msn.save()
        messages.add_message(request, messages.SUCCESS,'Creado con exito')
    mensajes = Mensaje.objects.all()        
    context= {'mensajes':mensajes}
    return render(request,"index.html",context)
    

#eliminar#
def delete_mensaje(request,id):
    try:
        msn = Mensaje.objects.get(id=id)
        msn.delete()
        messages.add_message(request, messages.SUCCESS, 'Borrado con éxito')
    except Mensaje.DoesNotExist:
        messages.add_message(request, messages.ERROR, 'No encontrado')

    return HttpResponseRedirect(reverse("index"))    

 #ACTUALIZAR
def edit_mensaje(request,id):
    try:
        msn = Mensaje.objects.get(id=id)
        mensajes = Mensaje.objects.all()
        context ={'mensajes':mensajes,'mensaje':msn}
        if request.POST:
            usuario =request.POST.get("usuario",False)
            rutina=request.POST.get("rutina",False)
            mensaje = request.POST.get("mensaje",False)
            foto = request.FILES.get("foto",False)
            borrar_foto =request.POST.get("borrar_foto",False)
            msn.usuario = usuario
            msn.rutina = rutina
            msn.mensaje = mensaje
            if foto:
                msn.foto = foto
            if borrar_foto:
                msn.foto = None
            msn.save()
            messages.add_message(request, messages.SUCCESS, 'Editado con éxito')
            return HttpResponseRedirect(reverse("index"))
        return render(request,"index.html",context)
    except Mensaje.DoesNotExist:
        messages.add_message(request, messages.ERROR, 'No encontrado')
    return HttpResponseRedirect(reverse("index"))


# Buscar #

Networks - Examen/API/templates/index.html
<!doctype html>
<html lang="es-cl">
  <head>
   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
   
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Registro de Rutinas</title>
  </head>
  <body style="background-color:#78e08f">
    <div >
      <nav class="navbar navbar-default navbar-dark" role="navigation" style="background-color:#27ae60;" >
          <!-- en la etiqueta nav el color de fondo es style="background-color"(a esta etiqueta se le puede cambiar el color a gusto)-->
          <ul class="nav nav-pills"  >
              <!-- en la etiqueta li para cambiar el color de texto se debe modificar lo que esta dentro de style="color:ColorModificable" para los textos-->
              <li class="nav-item"><a class="nav-link " href="{% url 'inicio'%}"style="color:#ecf0f1">Inicio</a></li>
              <li class="nav-item"><a class="nav-link " href="{% url 'proyecto:quienes_somos'%}"style="color:#ecf0f1">Quienes somos</a></li>
              <li class="nav-item"><a class="nav-link " href="{% url 'proyecto:mision'%}"style="color:#ecf0f1">Misión</a></li>
              <li class="nav-item"><a class="nav-link " href="{% url 'login' %}"style="color:#ecf0f1">Ingresar</a></li>
              <li class="nav-item"><a class="nav-link " href="{% url 'proyecto:contacto'%}"style="color:#ecf0f1">Contactenos</a></li>
              <li class="nav item"><a class="nav-link" href="{% url 'API:index'%}"style="color:#ecf0f1">Registro de Rutinas</a></li>
            </ul>
      </nav>
    </div>
    
    <div class="container">
        <h1>Registro de Rutinas</h1>
        {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger{%else%}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
    {% endfor %}
</ul>
{% endif %}
    </div>

    <form action="" method="post" enctype='multipart/form-data'>
        <div class="container">
            {% csrf_token %}
            <div class="form-group">
                <label for="usuario">Nombre</label>
                <input type="text" value="{{mensaje.usuario}}" name="usuario" placeholder="Ingrese su nombre" class="form-control">
            </div>
            <div>
              <label for="rutina">Rutina</label>
              <input type="text" value="{{mensaje.rutina}}" name="rutina" placeholder="Ingrese el nombre de la rutina" class="form-control">
            </div>
            
            <div class="form-group">
                <label for="mensaje">Mensaje</label>
                <textarea name="mensaje" rows="3" class="form-control">{{mensaje.mensaje}}</textarea>
            </div>
            
            {% if mensaje.foto %}
            <div class="form-group">
                <img src="{{mensaje.foto.url}}" width="200" alt="" srcset="">
            </div>
            <div class="form-check">
              <input type="checkbox" name="borrar_foto" class="form-check-input">
              <label for="borrar_foto"  class="form-check-label">Eliminar Foto</label>
            </div>    
            {% endif %}
            <div class="form-group">
                    <label for="foto">Foto</label>
                    <input type="file" accept="image/*" name="foto">
            </div>
            <input type="submit" class="btn btn-primary btn-lg"  value="Guardar">
            {% if mensaje %}
            <a href="{% url 'index' %}" class="btn btn-danger btn-lg">Volver</a>
            {% endif %}
        </div>
    </form>
    <br>
    <div class="container">
            <table class="table" id="tabla">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Foto</th>
                        <th scope="col">Usuario</th>
                        <th scope="col">Rutina</th>
                        <th scope="col">Mensaje</th>
                        <th scope="col"></th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for msn in mensajes %}
                      <tr>
                          
                        <th scope="row">{{msn.id}}</th>
                        {% if msn.foto %}
                        <td><img src="{{msn.foto.url}}" width="150" alt="" srcset=""></td>
                        {% else %}
                        <td><h4>No foto</h4></td>
                        {% endif %}
                        <td>{{msn.usuario}}</td>
                        <td>{{msn.rutina}}</td>
                        <td>{{msn.mensaje}}</td>
                        <td>
                              <a href="{% url 'API:edit_mensaje' msn.id %}" class="btn btn-warning">Editar</a>
                            <a href="{% url 'API:delete_mensaje' msn.id %}" class="btn btn-danger">Borrar</a>
                        </td>
                      </tr>
                      {% endfor %}
                     
                    </tbody>
                  </table>
                  <div align="center">
                    <img  src="{% static '../static/proyecto/img/icon.jpg'  %}" >
                  </div >
    </div>
    
    
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
  </body>
</html>